### ISSUE TITLE
residual computation in code disaccord with your TVCG paper

### ISSUE THREAD

**Issue by Tomas-Lee** [zju3dv/CoLi-BA#2]
The code in ba_block.h is "res.noalias()=a-Q.conjugate()*mea3d".
while the formula is $e_k=R_i\frac{a_{ij}}{||a_{ij}||}-\frac{\tilde{x_{ij}}}{||\tilde{x_{ij}}||}$ in your TVCG paper。
In my opinion, "a" in code seemingly accord with $\frac{a_{ij}}{||a_{ij}||}$, but "a" in your code has no R_i in the left
Could you please explicate?

**Comment by oneLOH** [comment]
Here 'res' is e'_k , not e_k.
![image](https://user-images.githubusercontent.com/26155071/199009855-0003c417-fa37-431e-baa2-bbf4e4334b6c.png)
