### ISSUE TITLE
Cannot reproduce similar time and avg_mse results with the paper.

### ISSUE THREAD

**Issue by liquorleaf** [zju3dv/CoLi-BA#3]
Hi,
I am trying to run the provided expamles. The source code has not been changed, but cannot reproduce the similar performance results with the paper. More exactly, I have tried two sequences seq01 and Alamo with all ceres, g2o and coli, but the results show that ceres is actually the fastest, g2o is more accurate with more time consumption, and coli has the worst time and avg_mse performance every time. I wonder if there are any bugs in the code.
I run the code on ubuntu 20.04, with an Intel i5-11260H @ 2.6GHz CPU. The number of thread (1) is not changed. Here are my results:
Test Data Seq01:
![2022-11-20 14-51-46屏幕截图](https://user-images.githubusercontent.com/69955263/202889830-3457e205-4572-4399-8a7c-34b80bd4deed.png)
![2022-11-20 14-52-15屏幕截图](https://user-images.githubusercontent.com/69955263/202889840-eec9e21c-c5b5-4d67-a76a-21a95e6abfca.png)
![2022-11-20 14-52-34屏幕截图](https://user-images.githubusercontent.com/69955263/202889843-3cf4525b-a84c-4747-be1e-537ee038ca57.png)
Alamo:
![2022-11-20 14-52-00屏幕截图](https://user-images.githubusercontent.com/69955263/202889853-c61eabe1-adfb-4ac5-a0fa-08739906931e.png)
![2022-11-20 14-52-23屏幕截图](https://user-images.githubusercontent.com/69955263/202889859-d040c460-20ed-4d1f-b121-9fd8c6bd3e1e.png)
![2022-11-20 14-52-46屏幕截图](https://user-images.githubusercontent.com/69955263/202889864-d833206b-603e-434e-831f-3b714c724ac9.png)

**Comment by oneLOH** [comment]
Please check whether code is running in RELEASE build. The slow speed may be due to this.

**Comment by liquorleaf** [comment]
> Please check whether code is running in RELEASE build. The slow speed may be due to this.

Thanks for your advice! Now we can reproduce the similar results for Seq00 and Seq01:
![2022-11-20 21-48-43屏幕截图](https://user-images.githubusercontent.com/69955263/202905981-a6411655-3cdb-43de-9c21-b80b2b456a6b.png)
![2022-11-20 21-48-59屏幕截图](https://user-images.githubusercontent.com/69955263/202905984-d0da9772-258e-42b6-9f7f-7caa0121f7b1.png)
![2022-11-20 21-49-11屏幕截图](https://user-images.githubusercontent.com/69955263/202905987-8b57b19b-02d5-46d0-93f6-f69ac70a0232.png)

However, for **Alamo**, the results remains confusing:
![2022-11-20 21-56-41屏幕截图](https://user-images.githubusercontent.com/69955263/202906225-f4dd5594-1b8f-40b6-aa17-f7f97aafc671.png)
![2022-11-20 21-57-16屏幕截图](https://user-images.githubusercontent.com/69955263/202906227-2acf151b-3326-46c7-a2cf-e6dbd31dbe60.png)
![2022-11-20 21-57-29屏幕截图](https://user-images.githubusercontent.com/69955263/202906229-a4f997fd-8d9c-4a71-bded-b3bda6ebafee.png)

It seems that ceres outperforms coli.
Please help us further if any idea on your mind. Thanks a lot!

**Comment by oneLOH** [comment]
Thank you for the information. 
1. The speed problem in Alamo.
Please chang the code in run_ba_ceres.cc.
` // solver_options.preconditioner_type = ceres::IDENTITY;`
`solver_options.preconditioner_type = ceres::SCHUR_JACOBI; `
  `solver_options.use_explicit_schur_complement = true;`
It is a bug of code, resulting ceres use implict schur complement (The implict schur complement may fast, but only suitable for PCG. Both g2o and coli use explicit manner). 
2. The accuracy problem in Alamo.
In the experiment, we will adjust the input noise so that the initial reprojection error is about 10 (mentioned in the paper).
In the current code, all sequences use the same noise(3e-4), which make some results different with the paper. You can try to use a larger noise parameter in Alamo.

The above problem will be solved later this week.

**Comment by oneLOH** [comment]
The code have been updated . I hope it will solve your problem. If you have any questions, please contact me : )

**Comment by liquorleaf** [comment]
> The code have been updated . I hope it will solve your problem. If you have any questions, please contact me : )

Thanks for your help! I'll try the new code then :+1:

**Comment by liquorleaf** [comment]
> The code have been updated . I hope it will solve your problem. If you have any questions, please contact me : )
Hi,
I've tried the new code with larger noise as suggested, and reproduced the expected results. Thank you again for the help so far!
